# Generated by Django 5.1.4 on 2025-06-16 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_invoice', models.BooleanField(default=True)),
                ('delete_invoice', models.BooleanField(default=True)),
                ('void_invoice', models.BooleanField(default=True)),
                ('mark_invoice_as_paid', models.BooleanField(default=True)),
                ('create_order', models.BooleanField(default=True)),
                ('delete_order', models.BooleanField(default=True)),
                ('create_estimate', models.BooleanField(default=True)),
                ('delete_estimate', models.BooleanField(default=True)),
                ('create_expense', models.BooleanField(default=True)),
                ('delete_expense', models.BooleanField(default=True)),
                ('turn_orders_into_invoices', models.BooleanField(default=True)),
                ('turn_estimates_into_invoices', models.BooleanField(default=True)),
                ('rebill_expenses', models.BooleanField(default=True)),
                ('send_sms_notification', models.BooleanField(default=True)),
                ('create_customer', models.BooleanField(default=True)),
                ('delete_customer', models.BooleanField(default=True)),
                ('import_customers', models.BooleanField(default=True)),
                ('create_product_service', models.BooleanField(default=True)),
                ('delete_product_service', models.BooleanField(default=True)),
                ('import_products', models.BooleanField(default=True)),
                ('run_reports', models.BooleanField(default=True)),
                ('generate_recurring_invoices', models.BooleanField(default=True)),
                ('create_purchase_order', models.BooleanField(default=True)),
                ('delete_purchase_order', models.BooleanField(default=True)),
                ('modify_invoice_settings', models.BooleanField(default=True)),
                ('modify_order_settings', models.BooleanField(default=True)),
                ('modify_estimate_settings', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
