# Generated by Django 5.1.4 on 2025-06-16 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModulePermission',
            new_name='Modules',
        ),
    ]
