# Generated by Django 5.1.4 on 2025-06-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0002_rename_modulepermission_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('sales_tax_reg_no', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='company_logos/')),
                ('print', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingSoftware_App.companies')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=50, null=True)),
                ('currency_sign', models.CharField(max_length=10, null=True)),
                ('currency_sign_placement', models.CharField(max_length=20, null=True)),
                ('decimal_separator', models.CharField(max_length=5, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingSoftware_App.companies')),
            ],
        ),
        migrations.CreateModel(
            name='DateFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingSoftware_App.companies')),
            ],
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type_first', models.CharField(max_length=50, null=True)),
                ('tax1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tax2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tax2_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tax_type_second', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingSoftware_App.companies')),
            ],
        ),
    ]
