# Generated by Django 5.1.4 on 2025-06-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0003_companies_companylogo_currencysettings_dateformat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrencySettings',
            new_name='Currency',
        ),
        migrations.RenameModel(
            old_name='TaxSettings',
            new_name='Tax',
        ),
    ]
