# Generated by Django 5.1.4 on 2025-06-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0004_rename_currencysettings_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='print_tax1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tax',
            name='print_tax2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_type_first',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_type_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
