# Generated by Django 5.1.4 on 2025-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0005_tax_print_tax1_tax_print_tax2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, null=True)),
                ('page_size', models.CharField(max_length=100, null=True)),
                ('right_margin_mm', models.IntegerField(null=True)),
                ('invoice_block_shift_left_mm', models.IntegerField(null=True)),
                ('invoice_block_shift_top_mm', models.IntegerField(null=True)),
            ],
        ),
    ]
