# Generated by Django 5.1.4 on 2025-06-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0006_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCostList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_color', models.CharField(max_length=100, null=True)),
                ('attachment_type', models.CharField(max_length=100, null=True)),
                ('invoice_numbering', models.BooleanField(default=False)),
                ('order_numbering', models.BooleanField(default=False)),
                ('estimate_numbering', models.BooleanField(default=False)),
                ('porder_numbering', models.BooleanField(default=False)),
                ('confirmation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=255, null=True)),
                ('days', models.IntegerField(null=True)),
            ],
        ),
    ]
