# Generated by Django 5.1.4 on 2025-06-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0007_extracostlist_miscellaneous_paymentterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Predefined_text', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='extracostlist',
            name='cost_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
