# Generated by Django 5.1.4 on 2025-06-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0008_predefinedtext_alter_extracostlist_cost_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predefinedtext',
            old_name='Predefined_text',
            new_name='predefined_text',
        ),
    ]
