# Generated by Django 5.1.4 on 2025-06-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0009_rename_predefined_text_predefinedtext_predefined_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneous',
            name='confirmation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='estimate_numbering',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='invoice_numbering',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='order_numbering',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='porder_numbering',
            field=models.BooleanField(default=True),
        ),
    ]
