# Generated by Django 5.1.4 on 2025-06-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0010_alter_miscellaneous_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneous',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
