# Generated by Django 5.1.4 on 2025-06-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0011_miscellaneous_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number_prefix', models.CharField(default='INV', max_length=50)),
                ('invoice_starting_number', models.IntegerField(default=1)),
                ('header_background_color', models.CharField(default='warning', max_length=50)),
                ('invoice_label', models.CharField(default='Invoice', max_length=100)),
                ('invoice_number_label', models.CharField(default='Invoice #', max_length=100)),
                ('invoice_date_label', models.CharField(default='Invoice Date', max_length=100)),
                ('due_date_label', models.CharField(default='Due Date', max_length=100)),
                ('order_ref_label', models.CharField(default='Order #', max_length=100)),
                ('terms_label', models.CharField(default='Terms', max_length=100)),
                ('ship_to_label', models.CharField(default='Ship To', max_length=100)),
                ('id_sku_label', models.CharField(default='ID/SKU', max_length=100)),
                ('product_service_label', models.CharField(default='Product/Service', max_length=100)),
                ('quantity_label', models.CharField(default='Quantity', max_length=100)),
                ('description_label', models.CharField(default='Description', max_length=100)),
                ('unit_price_label', models.CharField(default='Unit Price', max_length=100)),
                ('price_label', models.CharField(default='Price', max_length=100)),
                ('subtotal_label', models.CharField(default='Subtotal', max_length=100)),
                ('discount_label', models.CharField(default='Discount', max_length=100)),
                ('discount_rate', models.CharField(default='Discount Rate', max_length=100)),
                ('tax1', models.CharField(default='Tax 1', max_length=100, verbose_name='Tax 1')),
                ('tax2', models.CharField(default='Tax 2', max_length=100, verbose_name='Tax 2')),
                ('invoice_total', models.CharField(default='Invoice Total', max_length=100)),
                ('total_paid', models.CharField(default='Total Paid', max_length=100)),
                ('balance', models.CharField(default='Balance', max_length=100)),
                ('terms_and_conditions', models.CharField(default='Terms and Conditions', max_length=100)),
                ('tax_exempted', models.CharField(default='Tax Exempted', max_length=100)),
                ('page', models.CharField(default='Page', max_length=100)),
                ('of', models.CharField(default='of', max_length=100)),
                ('invoice_terms_footer', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_settings', to='BillingSoftware_App.template')),
            ],
        ),
    ]
