# Generated by Django 5.1.4 on 2025-06-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0012_invoicesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesettings',
            name='header_background_color',
            field=models.CharField(default='orange', max_length=50),
        ),
    ]
