# Generated by Django 5.1.4 on 2025-06-23 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0013_alter_invoicesettings_header_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesettings',
            name='header_background_color',
            field=models.CharField(default='#ffa500', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('order_starting_number', models.IntegerField(default=1)),
                ('header_background_color', models.CharField(blank=True, max_length=20, null=True)),
                ('order_label', models.CharField(blank=True, max_length=100, null=True)),
                ('order_number_label', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date_label', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date_label', models.CharField(blank=True, max_length=100, null=True)),
                ('order_to', models.CharField(blank=True, max_length=255, null=True)),
                ('order_total', models.CharField(blank=True, max_length=100, null=True)),
                ('order_terms_footer', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingSoftware_App.template')),
            ],
        ),
    ]
