# Generated by Django 5.1.4 on 2025-06-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0014_alter_invoicesettings_header_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesettings',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='BillingSoftware_App.template'),
        ),
        migrations.CreateModel(
            name='EstimateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number_prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('estimate_starting_number', models.IntegerField(default=1)),
                ('header_background_color', models.CharField(blank=True, max_length=20, null=True)),
                ('estimate_label', models.CharField(default='Estimate', max_length=50)),
                ('estimate_number_label', models.CharField(default='Estimate Number', max_length=50)),
                ('estimate_date_label', models.CharField(default='Estimate Date', max_length=50)),
                ('due_date_label', models.CharField(default='Due Date', max_length=50)),
                ('estimate_to', models.CharField(default='Estimate To', max_length=100)),
                ('order_total', models.CharField(default='Order Total', max_length=50)),
                ('estimate_terms_footer', models.TextField(blank=True, null=True)),
                ('template_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_settings', to='BillingSoftware_App.template')),
            ],
        ),
    ]
