# Generated by Django 5.1.4 on 2025-06-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0015_alter_invoicesettings_template_estimatesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimatesettings',
            old_name='order_total',
            new_name='estimate_total',
        ),
    ]
