# Generated by Django 5.1.4 on 2025-06-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0016_rename_order_total_estimatesettings_estimate_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesettings',
            name='estimate_total',
            field=models.CharField(default='Estimate Total', max_length=50),
        ),
    ]
