# Generated by Django 5.1.4 on 2025-06-24 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0017_alter_estimatesettings_estimate_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesettings',
            name='due_date_label',
            field=models.CharField(default='Due Date', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesettings',
            name='estimate_date_label',
            field=models.CharField(default='Estimate Date', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesettings',
            name='estimate_label',
            field=models.CharField(default='Estimate', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesettings',
            name='estimate_number_label',
            field=models.CharField(default='Estimate Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesettings',
            name='estimate_starting_number',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesettings',
            name='estimate_to',
            field=models.CharField(default='Estimate To', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesettings',
            name='estimate_total',
            field=models.CharField(default='Estimate Total', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesettings',
            name='template_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimate_settings', to='BillingSoftware_App.template'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='balance',
            field=models.CharField(default='Balance', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='description_label',
            field=models.CharField(default='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='discount_label',
            field=models.CharField(default='Discount', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='discount_rate',
            field=models.CharField(default='Discount Rate', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='due_date_label',
            field=models.CharField(default='Due Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='header_background_color',
            field=models.CharField(default='#ffa500', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='id_sku_label',
            field=models.CharField(default='ID/SKU', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='invoice_date_label',
            field=models.CharField(default='Invoice Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='invoice_label',
            field=models.CharField(default='Invoice', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='invoice_number_label',
            field=models.CharField(default='Invoice #', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='invoice_number_prefix',
            field=models.CharField(default='INV', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='invoice_starting_number',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='invoice_total',
            field=models.CharField(default='Invoice Total', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='of',
            field=models.CharField(default='of', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='order_ref_label',
            field=models.CharField(default='Order #', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='page',
            field=models.CharField(default='Page', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='price_label',
            field=models.CharField(default='Price', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='product_service_label',
            field=models.CharField(default='Product/Service', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='quantity_label',
            field=models.CharField(default='Quantity', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='ship_to_label',
            field=models.CharField(default='Ship To', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='subtotal_label',
            field=models.CharField(default='Subtotal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='tax1',
            field=models.CharField(default='Tax 1', max_length=100, null=True, verbose_name='Tax 1'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='tax2',
            field=models.CharField(default='Tax 2', max_length=100, null=True, verbose_name='Tax 2'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='tax_exempted',
            field=models.CharField(default='Tax Exempted', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='terms_and_conditions',
            field=models.CharField(default='Terms and Conditions', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='terms_label',
            field=models.CharField(default='Terms', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='total_paid',
            field=models.CharField(default='Total Paid', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='unit_price_label',
            field=models.CharField(default='Unit Price', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='order_starting_number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
