# Generated by Django 5.1.4 on 2025-06-24 07:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0018_alter_estimatesettings_due_date_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesettings',
            name='estimate_terms_footer',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='invoice_terms_footer',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='order_terms_footer',
            field=models.TextField(blank=True, default='P.ORD'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PurchaseOrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porder_number_prefix', models.CharField(blank=True, default='P.ORD', max_length=20)),
                ('porder_starting_number', models.IntegerField(default=1, null=True)),
                ('header_background_color', models.CharField(blank=True, default='#ffa500', max_length=20)),
                ('porder_label', models.CharField(blank=True, default='Purchase Order', max_length=50)),
                ('porder_number_label', models.CharField(blank=True, default='Purchase Order #', max_length=50)),
                ('porder_date_label', models.CharField(blank=True, default='Purchase Order Date', max_length=50)),
                ('due_date_label', models.CharField(blank=True, default='Due Date', max_length=50)),
                ('porder_to', models.CharField(blank=True, default='Vendor', max_length=50)),
                ('delivery_to', models.CharField(blank=True, default='Delivery To', max_length=50)),
                ('porder_total', models.CharField(blank=True, default='Purchase Order Total', max_length=50)),
                ('porder_terms_footer', models.TextField(blank=True)),
                ('template_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillingSoftware_App.template')),
            ],
        ),
    ]
