# Generated by Django 3.2.25 on 2025-06-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0019_alter_estimatesettings_estimate_terms_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='invoice_to_label',
            field=models.CharField(default='Invoice To', max_length=100, null=True),
        ),
    ]
