# Generated by Django 3.2.25 on 2025-06-27 08:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0020_invoicesettings_invoice_to_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_receipt_label', models.CharField(default='Payment Receipt', max_length=100)),
                ('payment_for_invoice_label', models.CharField(default='Payment for Invoice #', max_length=100)),
                ('amount_received_from_label', models.CharField(default='Amount received from:', max_length=100)),
                ('description_label', models.CharField(default='Description:', max_length=100)),
                ('payment_received_in_label', models.CharField(default='Payment Received in:', max_length=100)),
                ('payment_receipt_number_label', models.CharField(default='Payment Receipt #', max_length=100)),
                ('payment_date_label', models.CharField(default='Payment Date:', max_length=100)),
                ('payment_amount_label', models.CharField(default='Payment Amount:', max_length=100)),
                ('total_amount_due_label', models.CharField(default='Total Amount Due', max_length=100)),
                ('total_paid_label', models.CharField(default='Total Paid', max_length=100)),
                ('balance_due_label', models.CharField(default='Balance Due', max_length=100)),
                ('payment_receipt_prefix', models.CharField(default='RCPT', max_length=20)),
                ('paid_image', models.ImageField(blank=True, null=True, upload_to='payment_images/')),
                ('show_paid_on_fully_paid', models.BooleanField(default=False)),
                ('send_receipt_email_after_payment', models.BooleanField(default=False)),
                ('attach_invoice_to_receipt_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField()),
                ('html', ckeditor.fields.RichTextField()),
                ('template_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingSoftware_App.template')),
            ],
        ),
    ]
