# Generated by Django 3.2.25 on 2025-06-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0021_emailtemplate_paymentsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
