# Generated by Django 5.0.7 on 2025-07-04 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0022_alter_emailtemplate_template_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('business_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('ship_to_name', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('contact_person', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(max_length=20)),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_mobile_number', models.CharField(max_length=20)),
                ('ship_to_contact_person', models.CharField(max_length=255)),
                ('ship_to_email_address', models.EmailField(max_length=254)),
                ('ship_to_telephone_number', models.CharField(max_length=20)),
                ('ship_to_fax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('specific_tax1_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('specific_tax2_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('customer_type', models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('both', 'Both')], max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingSoftware_App.customercategory')),
            ],
        ),
    ]
