# Generated by Django 5.0.7 on 2025-07-09 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSoftware_App', '0023_customercategory_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('sms_number', models.CharField(max_length=20)),
                ('ship_to_name', models.CharField(max_length=255)),
                ('ship_to_address', models.TextField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_check', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order_reference', models.CharField(blank=True, max_length=255)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('specific_tax1_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('specific_tax2_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sales_person', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('tax_exempted', models.BooleanField(default=False)),
                ('emailed_on', models.DateTimeField(blank=True, null=True)),
                ('printed_on', models.DateTimeField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_period', models.IntegerField(blank=True, null=True)),
                ('recurring_intervel', models.CharField(blank=True, max_length=100)),
                ('next_invoice', models.DateField(blank=True, null=True)),
                ('stop_recurring_after', models.BooleanField(default=False)),
                ('stop_recurring_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('terms_text', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True)),
                ('title_head', models.CharField(blank=True, max_length=255)),
                ('page_header_text', models.CharField(blank=True, max_length=255)),
                ('footer_text', models.TextField(blank=True)),
                ('extra_cost_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BillingSoftware_App.extracostlist')),
                ('invoice_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingSoftware_App.customer')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BillingSoftware_App.template')),
                ('terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BillingSoftware_App.paymentterms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
